"""empty message

Revision ID: 3136b01683b4
Revises: 2db13969d422
Create Date: 2018-12-16 15:03:01.530413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3136b01683b4'
down_revision = '2db13969d422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=50), nullable=True),
    sa.Column('rfid', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('person', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('person', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_person_username'), 'person', ['username'], unique=True)
    op.drop_column('person', 'rfid')
    op.drop_column('person', 'student_name')
    op.drop_column('person', 'student_id')
    op.drop_constraint(None, 'roll', type_='foreignkey')
    op.create_foreign_key(None, 'roll', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roll', type_='foreignkey')
    op.create_foreign_key(None, 'roll', 'person', ['student_id'], ['id'])
    op.add_column('person', sa.Column('student_id', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('student_name', sa.VARCHAR(length=50), nullable=True))
    op.add_column('person', sa.Column('rfid', sa.BLOB(), nullable=True))
    op.drop_index(op.f('ix_person_username'), table_name='person')
    op.drop_column('person', 'username')
    op.drop_column('person', 'password_hash')
    op.drop_table('student')
    # ### end Alembic commands ###
